# NB that the following annotation was generated by the annotate gem : 
# bundle exec annotate --position before
# adds comments re. the data model to the model file. 

# == Schema Information
#
# Table name: users
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  email      :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class User < ActiveRecord::Base
  
  # Interestingly, annotate doesn't like me adding the attr_accessible line, 
  # which the Rails tutorial suggested I add. 
  # apparently, it's been "extracted out of Rails into a gem."
  
  # note that we're supporting these items in the spec, so 
  # if these validations fail, the spec will let us know that the validation isn't working correctly. 
  
  validates :name, presence: true, length: { maximum: 50 } #NB that 'validates' is just a method like any other.
  validates :email, presence: true #and let's do the same for email. 
  validates :email, uniqueness: { case_sensitive: false } #enforce case-sensitive uniqueness on emails; case_sensitive implies "uniqueness: true"
  
  #YUSSSSS it's regular expression time. Let's validate some emails. 
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i #Ruby convention : all caps = constant
  validates :email, format: { with: VALID_EMAIL_REGEX }
  
end
